[features]
seeds = false
skip-lint = false
[programs.localnet]
simple_token_vault = "2dftvFuYB5H7GFKerZUESaiN6pvqXJgFuqMcQkf6q5ZP"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "./id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
